packages:
  - packages/*

catalog:
  '@babel/core': 7.28.6
  '@babel/preset-env': 7.28.6
  '@babel/preset-typescript': 7.28.5
  '@types/jest': 30.0.0
  '@types/node': 25.0.9
  '@typescript-eslint/eslint-plugin': 8.53.0
  '@typescript-eslint/parser': 8.53.0
  babel-jest: 30.2.0
  eslint: 9.39.2
  jest: 30.2.0
  typescript: 5.9.3

fetchRetryMaxtimeout: 10000

fetchRetryMintimeout: 1000
