packages:
  - packages/*
  - packages-origin/*

catalog:
  '@babel/core': 7.28.6
  '@babel/preset-env': 7.28.6
  '@babel/preset-typescript': 7.28.5
  '@sudoo/asynchronous': 2.4.0
  '@sudoo/io': 1.8.0
  '@sudoo/locale': 2.0.0
  '@sudoo/uuid': 1.1.0
  '@types/jest': 30.0.0
  '@types/node': 25.0.9
  '@typescript-eslint/eslint-plugin': 8.53.1
  '@typescript-eslint/parser': 8.53.1
  axios: 1.13.2
  babel-jest: 30.2.0
  body-parser: 2.2.2
  commander: 14.0.2
  cors: 2.8.5
  eslint: 9.39.2
  express: 5.2.1
  jest: 30.2.0
  ts-node: 10.9.2
  typescript: 5.9.3
  turbo: 2.7.5

fetchRetryMaxtimeout: 10000

fetchRetryMintimeout: 1000

onlyBuiltDependencies:
  - unrs-resolver
