packages:
  - packages/*
  - packages-origin/*

catalog:
  '@babel/core': 7.29.0
  '@babel/preset-env': 7.29.0
  '@babel/preset-typescript': 7.28.5
  '@sudoo/asynchronous': 2.4.0
  '@sudoo/io': 1.8.0
  '@sudoo/locale': 2.0.0
  '@sudoo/uuid': 1.1.0
  '@types/body-parser': 1.19.6
  '@types/cors': 2.8.19
  '@types/express': 5.0.6
  '@types/jest': 30.0.0
  '@types/node': 25.2.1
  '@typescript-eslint/eslint-plugin': 8.54.0
  '@typescript-eslint/parser': 8.54.0
  axios: 1.13.4
  babel-jest: 30.2.0
  body-parser: 2.2.2
  commander: 14.0.3
  cors: 2.8.6
  eslint: 9.39.2
  express: 5.2.1
  jest: 30.2.0
  ts-node: 10.9.2
  turbo: 2.8.3
  typescript: 5.9.3

fetchRetryMaxtimeout: 10000

fetchRetryMintimeout: 1000

onlyBuiltDependencies:
  - unrs-resolver
