/**
 * @author WMXPY
 * @namespace Document
 * @description Feature
 */

export enum IMBRICATE_DOCUMENT_FEATURE {

    DOCUMENT_PUT_PROPERTY = "DOCUMENT_PUT_PROPERTY",

    DOCUMENT_PUT_ANNOTATION = "DOCUMENT_PUT_ANNOTATION",
    DOCUMENT_REMOVE_ANNOTATION = "DOCUMENT_REMOVE_ANNOTATION",

    DOCUMENT_PUT_EDIT_RECORD = "DOCUMENT_PUT_EDIT_RECORD",
    DOCUMENT_GET_EDIT_RECORD = "DOCUMENT_GET_EDIT_RECORD",
}

export const fullSupportedDocumentFeatures: IMBRICATE_DOCUMENT_FEATURE[] = [

    IMBRICATE_DOCUMENT_FEATURE.DOCUMENT_PUT_PROPERTY,

    IMBRICATE_DOCUMENT_FEATURE.DOCUMENT_PUT_ANNOTATION,
    IMBRICATE_DOCUMENT_FEATURE.DOCUMENT_REMOVE_ANNOTATION,

    IMBRICATE_DOCUMENT_FEATURE.DOCUMENT_PUT_EDIT_RECORD,
    IMBRICATE_DOCUMENT_FEATURE.DOCUMENT_GET_EDIT_RECORD,
];

export const annotationExcludedDocumentFeatures: IMBRICATE_DOCUMENT_FEATURE[] = [

    IMBRICATE_DOCUMENT_FEATURE.DOCUMENT_PUT_PROPERTY,

    IMBRICATE_DOCUMENT_FEATURE.DOCUMENT_PUT_EDIT_RECORD,
    IMBRICATE_DOCUMENT_FEATURE.DOCUMENT_GET_EDIT_RECORD,
];

export const editRecordExcludedDocumentFeatures: IMBRICATE_DOCUMENT_FEATURE[] = [

    IMBRICATE_DOCUMENT_FEATURE.DOCUMENT_PUT_PROPERTY,

    IMBRICATE_DOCUMENT_FEATURE.DOCUMENT_PUT_ANNOTATION,
    IMBRICATE_DOCUMENT_FEATURE.DOCUMENT_REMOVE_ANNOTATION,
];

export const IMBRICATE_DOCUMENT_PRESET_FEATURES: Record<string, IMBRICATE_DOCUMENT_FEATURE[]> = {

    FULL_SUPPORTED_FEATURES: fullSupportedDocumentFeatures,
    ANNOTATION_EXCLUDED_FEATURES: annotationExcludedDocumentFeatures,
    EDIT_RECORD_EXCLUDED_FEATURES: editRecordExcludedDocumentFeatures,
};

export const checkImbricateDocumentFeatureSupported = (
    features: IMBRICATE_DOCUMENT_FEATURE[],
    feature: IMBRICATE_DOCUMENT_FEATURE,
): boolean => {

    return features.includes(feature);
};
