/**
 * @author WMXPY
 * @namespace Database
 * @description Feature
 */

export enum IMBRICATE_DATABASE_FEATURE {

    DATABASE_PUT_SCHEMA = "DATABASE_PUT_SCHEMA",

    DATABASE_CREATE_DOCUMENT = "DATABASE_CREATE_DOCUMENT",
    DATABASE_UPDATE_DOCUMENT = "DATABASE_UPDATE_DOCUMENT",
    DATABASE_DELETE_DOCUMENT = "DATABASE_DELETE_DOCUMENT",

    DATABASE_PUT_ANNOTATION = "DATABASE_PUT_ANNOTATION",
    DATABASE_REMOVE_ANNOTATION = "DATABASE_REMOVE_ANNOTATION",

    DATABASE_QUERY_DOCUMENT = "DATABASE_QUERY_DOCUMENT",
    DATABASE_COUNT_DOCUMENT = "DATABASE_COUNT_DOCUMENT",

    DATABASE_PUT_EDIT_RECORD = "DATABASE_PUT_EDIT_RECORD",
    DATABASE_GET_EDIT_RECORD = "DATABASE_GET_EDIT_RECORD",
}

export const fullSupportedFeatures: IMBRICATE_DATABASE_FEATURE[] = [

    IMBRICATE_DATABASE_FEATURE.DATABASE_PUT_SCHEMA,
    IMBRICATE_DATABASE_FEATURE.DATABASE_CREATE_DOCUMENT,
    IMBRICATE_DATABASE_FEATURE.DATABASE_UPDATE_DOCUMENT,
    IMBRICATE_DATABASE_FEATURE.DATABASE_DELETE_DOCUMENT,
    IMBRICATE_DATABASE_FEATURE.DATABASE_PUT_ANNOTATION,
    IMBRICATE_DATABASE_FEATURE.DATABASE_REMOVE_ANNOTATION,
    IMBRICATE_DATABASE_FEATURE.DATABASE_QUERY_DOCUMENT,
    IMBRICATE_DATABASE_FEATURE.DATABASE_COUNT_DOCUMENT,
    IMBRICATE_DATABASE_FEATURE.DATABASE_PUT_EDIT_RECORD,
    IMBRICATE_DATABASE_FEATURE.DATABASE_GET_EDIT_RECORD,
];
